Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('1','AC','Acre');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('2','AL','Alagoas');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('3','AP','Amapá');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('4','AM','Amazonas');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('5','BA','Bahia');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('6','CE','Ceara');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('7','DF','Distrito Federal');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('8','ES','Espirito Santo');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('9','RR','Roraima');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('10','GO','Goias');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('11','MA','Maranhão');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('12','MT','Matogrosso');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('13','MS','Matogrosso do Sul');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('14','MG','Minas Gerais');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('15','PA','Para');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('16','PB','Paraiba');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('17','PR','Parana');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('18','PE','Pernambuco');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('19','PI','Piaui');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('20','RJ','Rio de Janeiro');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('21','RN','Rio Grande do Norte');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('22','RS','Rio Grande do Sul');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('23','RO','Rondonia');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('24','TO','Tocantins');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('25','SC','Santa Catarina');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('26','SP','Sao Paulo');
Insert into TB_MUSA_ESTADO (ID_ESTADO,SI_SIGLA,DS_DESCRICAO) values ('27','SE','Sergipe');