-- MySQL Script generated by MySQL Workbench
-- 03/02/16 10:28:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema musa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `musa` ;

-- -----------------------------------------------------
-- Schema musa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `musa` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `musa` ;

-- -----------------------------------------------------
-- Table `hibernate_sequence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hibernate_sequence` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `hibernate_sequence` (
  `next_val` BIGINT(20) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_musa_estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_musa_estado` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_musa_estado` (
  `ID_ESTADO` BIGINT(20) NOT NULL,
  `DS_DESCRICAO` VARCHAR(255) NULL DEFAULT NULL,
  `SI_SIGLA` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ESTADO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_musa_cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_musa_cidade` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_musa_cidade` (
  `DS_DESCRICAO` VARCHAR(100) NULL DEFAULT NULL,
  `ID_CIDADE` BIGINT(255) NOT NULL,
  `FK_ESTADO` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CIDADE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_musa_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_musa_cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_musa_cliente` (
  `ID_CLIENTE` BIGINT(20) NOT NULL,
  `NU_CPF` VARCHAR(255) NULL DEFAULT NULL,
  `DT_NASCIMENTO` DATE NULL DEFAULT NULL,
  `FL_EXCLUIDO` BIT(1) NULL DEFAULT NULL,
  `DS_NOME` VARCHAR(255) NULL DEFAULT NULL,
  `NU_RG` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CLIENTE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_musa_contato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_musa_contato` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_musa_contato` (
  `ID_CONTATO` BIGINT(20) NOT NULL,
  `NU_DDD` VARCHAR(255) NULL DEFAULT NULL,
  `DS_EMAIL` VARCHAR(255) NULL DEFAULT NULL,
  `FL_EXCLUIDO` BIT(1) NULL DEFAULT NULL,
  `NU_TELEFONE` VARCHAR(255) NULL DEFAULT NULL,
  `FK_CLIENTE` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CONTATO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_musa_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_musa_endereco` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_musa_endereco` (
  `ID_ENDERECO` BIGINT(20) NOT NULL,
  `DS_BAIRRO` VARCHAR(255) NULL DEFAULT NULL,
  `NU_CEP` VARCHAR(11) NULL DEFAULT NULL,
  `FK_CIDADE` BIGINT(11) NULL DEFAULT NULL,
  `NU_NUMERO` VARCHAR(10) NULL DEFAULT NULL,
  `DS_RUA` VARCHAR(255) NULL DEFAULT NULL,
  `FK_ESTADO` BIGINT(20) NULL DEFAULT NULL,
  `FK_CLIENTE` BIGINT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_ENDERECO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_musa_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_musa_pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_musa_pedido` (
  `ID_PEDIDO` BIGINT(20) NOT NULL,
  `DT_PEDIDO` DATE NULL DEFAULT NULL,
  `FL_EXCLUIDO` BIT(1) NULL DEFAULT NULL,
  `FK_CLIENTE` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PEDIDO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_musa_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_musa_pagamento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_musa_pagamento` (
  `ID_PAGAMENTO` BIGINT(20) NOT NULL,
  `DT_PAGAMENTO` DATE NULL DEFAULT NULL,
  `DS_OBSERVACAO` VARCHAR(255) NULL DEFAULT NULL,
  `NU_VALOR_PAGO` DECIMAL(19,2) NULL DEFAULT NULL,
  `NU_VALOR_RESTANTE` DECIMAL(19,2) NULL DEFAULT NULL,
  `FK_PEDIDO` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PAGAMENTO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_musa_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_musa_produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_musa_produto` (
  `ID_PRODUTO` BIGINT(20) NOT NULL,
  `DS_PRODUTO` VARCHAR(255) NULL DEFAULT NULL,
  `FL_EXCLUIDO` BIT(1) NULL DEFAULT NULL,
  `NU_PRECO_CUSTO` FLOAT NULL DEFAULT NULL,
  `NU_PRECO_VENDA` FLOAT NULL DEFAULT NULL,
  `FK_PEDIDO` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PRODUTO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
